### ISSUE TITLE
examples for matrix

### ISSUE THREAD

**Issue by sailseem** [heilandd/NFCN#1]
Dear，
    Sorry to bother， can you show me an example for these two matrix or just head of matrix？ It's kind of confused by looking at the explanation.

--Matrix_basis: Gene Expression Matrix with cells as colnames and rawnames as rownames
--Matrix_target: Gene Expression Matrix with cells as colnames and rawnames as rownames

Thanks a lot,
Fan

**Comment by heilandd** [comment]
Sorry for the typo:) ...  genes as rownames .... In a couple of days the new version of NFCN will be launched. It will be a fully R package supporting all most common formats such as Seurat, monocle3 and SPATA.

**Comment by sailseem** [comment]
looking forward to that！！！

**Comment by sailseem** [comment]
I am just wondering when the new fully packed R version of NFCN gonna be launched?   Sorry to bother you, and thanks for your reply.

**Comment by heilandd** [comment]
It is almost finished, the tutorials and dokumentation are pending, if you like I can share the beta version with you and you can test den help to further develop it. Send me a request per mail: dieter.henrik.heiland@uniklinik-freiburg.de, I can share the package with you.

**Comment by heilandd** [comment]
https://github.com/heilandd/NFCN2
